$dirs = @(
    "src/assets"
    "src/components/common"
    "src/components/layout"
    "src/components/ui"
    "src/layouts"
    "src/pages/super-admin"
    "src/pages/admin"
    "src/pages/patient"
    "src/pages/student"
    "src/pages/auth"
    "src/pages/common"
    "src/routes"
    "src/context"
    "src/hooks"
    "src/services"
    "src/utils"
    "src/store"
)
foreach ($dir in $dirs) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }

$files = @(
    "src/layouts/SuperAdminLayout.jsx"
    "src/layouts/AdminLayout.jsx"
    "src/layouts/PatientLayout.jsx"
    "src/layouts/StudentLayout.jsx"
    "src/pages/super-admin/Dashboard.jsx"
    "src/pages/super-admin/Users.jsx"
    "src/pages/super-admin/Settings.jsx"
    "src/pages/admin/Dashboard.jsx"
    "src/pages/admin/Patients.jsx"
    "src/pages/admin/Appointments.jsx"
    "src/pages/patient/Dashboard.jsx"
    "src/pages/patient/Reports.jsx"
    "src/pages/patient/Appointments.jsx"
    "src/pages/student/Dashboard.jsx"
    "src/pages/student/Courses.jsx"
    "src/pages/student/Profile.jsx"
    "src/pages/auth/Login.jsx"
    "src/pages/auth/Register.jsx"
    "src/pages/common/NotFound.jsx"
    "src/pages/common/Unauthorized.jsx"
    "src/routes/AppRoutes.jsx"
    "src/routes/ProtectedRoute.jsx"
    "src/routes/RoleBasedRoute.jsx"
    "src/context/AuthContext.jsx"
    "src/context/UserContext.jsx"
    "src/hooks/useAuth.js"
    "src/hooks/useRole.js"
    "src/services/api.js"
    "src/services/authService.js"
    "src/services/userService.js"
    "src/utils/constants.js"
    "src/utils/helpers.js"
)
foreach ($file in $files) { New-Item -ItemType File -Force -Path $file | Out-Null }
